// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SerializersCompare.Serializers
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class InheritedEntityAvro : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""InheritedEntityAvro"",""namespace"":""SerializersCompare.Serializers"",""fields"":[{""name"":""LargeIcon"",""type"":""bytes""},{""name"":""Message"",""type"":""string""},{""name"":""FunctionCall"",""type"":""string""},{""name"":""Parameters"",""type"":""string""},{""name"":""Name"",""type"":""string""},{""name"":""EmployeeId"",""type"":""int""},{""name"":""RaiseRate"",""type"":""float""},{""name"":""AddressLine1"",""type"":""string""},{""name"":""AddressLine2"",""type"":""string""},{""name"":""Icon"",""type"":""bytes""}]}");
		private byte[] _LargeIcon;
		private string _Message;
		private string _FunctionCall;
		private string _Parameters;
		private string _Name;
		private int _EmployeeId;
		private float _RaiseRate;
		private string _AddressLine1;
		private string _AddressLine2;
		private byte[] _Icon;
		public virtual Schema Schema
		{
			get
			{
				return InheritedEntityAvro._SCHEMA;
			}
		}
		public byte[] LargeIcon
		{
			get
			{
				return this._LargeIcon;
			}
			set
			{
				this._LargeIcon = value;
			}
		}
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				this._Message = value;
			}
		}
		public string FunctionCall
		{
			get
			{
				return this._FunctionCall;
			}
			set
			{
				this._FunctionCall = value;
			}
		}
		public string Parameters
		{
			get
			{
				return this._Parameters;
			}
			set
			{
				this._Parameters = value;
			}
		}
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		public int EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				this._EmployeeId = value;
			}
		}
		public float RaiseRate
		{
			get
			{
				return this._RaiseRate;
			}
			set
			{
				this._RaiseRate = value;
			}
		}
		public string AddressLine1
		{
			get
			{
				return this._AddressLine1;
			}
			set
			{
				this._AddressLine1 = value;
			}
		}
		public string AddressLine2
		{
			get
			{
				return this._AddressLine2;
			}
			set
			{
				this._AddressLine2 = value;
			}
		}
		public byte[] Icon
		{
			get
			{
				return this._Icon;
			}
			set
			{
				this._Icon = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.LargeIcon;
			case 1: return this.Message;
			case 2: return this.FunctionCall;
			case 3: return this.Parameters;
			case 4: return this.Name;
			case 5: return this.EmployeeId;
			case 6: return this.RaiseRate;
			case 7: return this.AddressLine1;
			case 8: return this.AddressLine2;
			case 9: return this.Icon;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.LargeIcon = (System.Byte[])fieldValue; break;
			case 1: this.Message = (System.String)fieldValue; break;
			case 2: this.FunctionCall = (System.String)fieldValue; break;
			case 3: this.Parameters = (System.String)fieldValue; break;
			case 4: this.Name = (System.String)fieldValue; break;
			case 5: this.EmployeeId = (System.Int32)fieldValue; break;
			case 6: this.RaiseRate = (System.Single)fieldValue; break;
			case 7: this.AddressLine1 = (System.String)fieldValue; break;
			case 8: this.AddressLine2 = (System.String)fieldValue; break;
			case 9: this.Icon = (System.Byte[])fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
