/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

public partial class MultiplicationService {
  /// <summary>
  /// Thrift doesn't support object/struct inheritence (see http://thrift.apache.org/docs/features/)
  /// So we have to manually define the resulting inherited structure here
  /// 
  /// To build the code-gen .cs files run
  /// <proj root>\packages\Thrift.0.9.0.0\tools\thrift-0.9.0.exe -gen csharp SimpleAndInheritedEntity.thrift
  /// 
  /// You need to have NuGet restore the packages to have those tools because Thrift is a NuGet package
  /// in this project
  /// </summary>
  public interface Iface {
    int multiply(int n1, int n2);
    #if SILVERLIGHT
    IAsyncResult Begin_multiply(AsyncCallback callback, object state, int n1, int n2);
    int End_multiply(IAsyncResult asyncResult);
    #endif
  }

  /// <summary>
  /// Thrift doesn't support object/struct inheritence (see http://thrift.apache.org/docs/features/)
  /// So we have to manually define the resulting inherited structure here
  /// 
  /// To build the code-gen .cs files run
  /// <proj root>\packages\Thrift.0.9.0.0\tools\thrift-0.9.0.exe -gen csharp SimpleAndInheritedEntity.thrift
  /// 
  /// You need to have NuGet restore the packages to have those tools because Thrift is a NuGet package
  /// in this project
  /// </summary>
  public class Client : Iface {
    public Client(TProtocol prot) : this(prot, prot)
    {
    }

    public Client(TProtocol iprot, TProtocol oprot)
    {
      iprot_ = iprot;
      oprot_ = oprot;
    }

    protected TProtocol iprot_;
    protected TProtocol oprot_;
    protected int seqid_;

    public TProtocol InputProtocol
    {
      get { return iprot_; }
    }
    public TProtocol OutputProtocol
    {
      get { return oprot_; }
    }


    
    #if SILVERLIGHT
    public IAsyncResult Begin_multiply(AsyncCallback callback, object state, int n1, int n2)
    {
      return send_multiply(callback, state, n1, n2);
    }

    public int End_multiply(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      return recv_multiply();
    }

    #endif

    public int multiply(int n1, int n2)
    {
      #if !SILVERLIGHT
      send_multiply(n1, n2);
      return recv_multiply();

      #else
      var asyncResult = Begin_multiply(null, null, n1, n2);
      return End_multiply(asyncResult);

      #endif
    }
    #if SILVERLIGHT
    public IAsyncResult send_multiply(AsyncCallback callback, object state, int n1, int n2)
    #else
    public void send_multiply(int n1, int n2)
    #endif
    {
      oprot_.WriteMessageBegin(new TMessage("multiply", TMessageType.Call, seqid_));
      multiply_args args = new multiply_args();
      args.N1 = n1;
      args.N2 = n2;
      args.Write(oprot_);
      oprot_.WriteMessageEnd();
      #if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
      oprot_.Transport.Flush();
      #endif
    }

    public int recv_multiply()
    {
      TMessage msg = iprot_.ReadMessageBegin();
      if (msg.Type == TMessageType.Exception) {
        TApplicationException x = TApplicationException.Read(iprot_);
        iprot_.ReadMessageEnd();
        throw x;
      }
      multiply_result result = new multiply_result();
      result.Read(iprot_);
      iprot_.ReadMessageEnd();
      if (result.__isset.success) {
        return result.Success;
      }
      throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "multiply failed: unknown result");
    }

  }
  public class Processor : TProcessor {
    public Processor(Iface iface)
    {
      iface_ = iface;
      processMap_["multiply"] = multiply_Process;
    }

    protected delegate void ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot);
    private Iface iface_;
    protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

    public bool Process(TProtocol iprot, TProtocol oprot)
    {
      try
      {
        TMessage msg = iprot.ReadMessageBegin();
        ProcessFunction fn;
        processMap_.TryGetValue(msg.Name, out fn);
        if (fn == null) {
          TProtocolUtil.Skip(iprot, TType.Struct);
          iprot.ReadMessageEnd();
          TApplicationException x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
          oprot.WriteMessageBegin(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID));
          x.Write(oprot);
          oprot.WriteMessageEnd();
          oprot.Transport.Flush();
          return true;
        }
        fn(msg.SeqID, iprot, oprot);
      }
      catch (IOException)
      {
        return false;
      }
      return true;
    }

    public void multiply_Process(int seqid, TProtocol iprot, TProtocol oprot)
    {
      multiply_args args = new multiply_args();
      args.Read(iprot);
      iprot.ReadMessageEnd();
      multiply_result result = new multiply_result();
      result.Success = iface_.multiply(args.N1, args.N2);
      oprot.WriteMessageBegin(new TMessage("multiply", TMessageType.Reply, seqid)); 
      result.Write(oprot);
      oprot.WriteMessageEnd();
      oprot.Transport.Flush();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class multiply_args : TBase
  {
    private int _n1;
    private int _n2;

    public int N1
    {
      get
      {
        return _n1;
      }
      set
      {
        __isset.n1 = true;
        this._n1 = value;
      }
    }

    public int N2
    {
      get
      {
        return _n2;
      }
      set
      {
        __isset.n2 = true;
        this._n2 = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool n1;
      public bool n2;
    }

    public multiply_args() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              N1 = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              N2 = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("multiply_args");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.n1) {
        field.Name = "n1";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(N1);
        oprot.WriteFieldEnd();
      }
      if (__isset.n2) {
        field.Name = "n2";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(N2);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("multiply_args(");
      sb.Append("N1: ");
      sb.Append(N1);
      sb.Append(",N2: ");
      sb.Append(N2);
      sb.Append(")");
      return sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class multiply_result : TBase
  {
    private int _success;

    public int Success
    {
      get
      {
        return _success;
      }
      set
      {
        __isset.success = true;
        this._success = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool success;
    }

    public multiply_result() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 0:
            if (field.Type == TType.I32) {
              Success = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("multiply_result");
      oprot.WriteStructBegin(struc);
      TField field = new TField();

      if (this.__isset.success) {
        field.Name = "Success";
        field.Type = TType.I32;
        field.ID = 0;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Success);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("multiply_result(");
      sb.Append("Success: ");
      sb.Append(Success);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
